# Generated by Django 2.1.2 on 2018-11-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20181101_1224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
